Feature/license registration
IanisT227/ianis-internship-scooterapp pull request #7
Opened 2022-09-12 12:40 UTC by IanisT227

License registration is now integrated in the application flow. I've tried using observer and mutablelivedata and removing any bussiness logic as much as possible, so if there is any place where I could've done that please let me know.

2022-09-15 09:29 UTC, catadarjan-tapptitude requested changes

2022-09-15 09:29 UTC, catadarjan-tapptitude commented on app/src/main/java/com/internship/move/feature/licenseRegistration/LicenseInstructionsFragment.kt
> +    private val takeImageResult = registerForActivityResult(ActivityResultContracts.TakePicture()) { isSuccess ->
Prefer having fields at the top of the class (same comment applies to `latestTmpUri`)
Also, I'd create a method `initTakeImageResult` to instantiate this instead of having the entire code block in the fields area.

2022-09-15 09:29 UTC, catadarjan-tapptitude commented on app/src/main/java/com/internship/move/feature/licenseRegistration/LicenseInstructionsFragment.kt
> +        val tmpFile = File.createTempFile("tmp_image_file", ".png").apply {
I'd extract these string values to companion object fields

2022-09-15 09:29 UTC, catadarjan-tapptitude commented on app/src/main/java/com/internship/move/feature/licenseRegistration/LicenseInstructionsFragment.kt
> +
Extra empty line

2022-09-15 09:29 UTC, catadarjan-tapptitude commented on app/src/main/java/com/internship/move/feature/licenseRegistration/LicenseInstructionsFragment.kt
> +                        LicenseItem(args.userData.token, File(imageUri.path.toString()))
Instead of having imageUri as a separate variable, you can just use the `uri` from this let. It looks to me like it's the same thing, and you don't need to keep it in sync

2022-09-15 09:29 UTC, catadarjan-tapptitude commented on app/src/main/java/com/internship/move/feature/licenseRegistration/LicenseInstructionsFragment.kt
> +        if (isSuccess) {
Here's some cool syntax sugar
Since you don't do anything on `else` you can quit the method on failure. This way you also reduce indentation
`if (!isSuccess) return@registerForActivityResult`

2022-09-15 09:29 UTC, catadarjan-tapptitude commented on app/src/main/java/com/internship/move/feature/licenseRegistration/LicenseInstructionsFragment.kt
> +    private fun initViews() {
I see you're just setting static strings here. How come you're not putting the initial values in xml file directly?

2022-09-15 09:29 UTC, catadarjan-tapptitude commented on app/src/main/java/com/internship/move/feature/licenseRegistration/LicenseItem.kt
> +    val image: File
A `File` object is a bit bigand complex to pe parcelized imo
Since you're using this data class as navigation args, you can instead have the uri here and create the File object in the receiving Fragment

2022-09-15 09:29 UTC, catadarjan-tapptitude commented on app/src/main/java/com/internship/move/feature/licenseRegistration/LicenseRegistrationViewModel.kt
> +
Extra empty line

2022-09-15 09:29 UTC, catadarjan-tapptitude commented on app/src/main/java/com/internship/move/feature/licenseRegistration/LicenseRegistrationViewModel.kt
> +    val licenseResponse: MutableLiveData<User?> = MutableLiveData()
I know we talked about this, but I'll leave the comment, so you have a written explanation and example to refer to:

For MutableLiveData you'll want to use LiveData backing fields, such that the value cannot be set from outside the ViewModel
```
private val _licenseResponse = MutableLiveData<User?>()
    val licenseResponse: LiveData<User?> 
        get() = _licenseResponse
```
You'll use `_licenseResponse` in the VM to set and get values, but in fragment you'll use `licenseResponse` to get and observe values

2022-09-15 09:29 UTC, catadarjan-tapptitude commented on app/src/main/java/com/internship/move/feature/licenseRegistration/LicenseRegistrationViewModel.kt
> +    val licenseResponse: MutableLiveData<User?> = MutableLiveData()
You can apply this everywhere else if you want. But I suggest you change it here and keep it in mind for the future

2022-09-15 09:29 UTC, catadarjan-tapptitude commented on app/src/main/java/com/internship/move/feature/licenseRegistration/LicenseRegistrationViewModel.kt
> +
Extra empty line

2022-09-15 09:29 UTC, catadarjan-tapptitude commented on app/src/main/java/com/internship/move/feature/licenseRegistration/LicenseRegistrationViewModel.kt
> +                    token = "Bearer $token",
You'll want to use an interceptor to set the token. This is because after login/register, most API calls will require it and you want to set it in a single place to ensure consistency

2022-09-15 09:29 UTC, catadarjan-tapptitude commented on app/src/main/java/com/internship/move/feature/licenseRegistration/LicenseRegistrationViewModel.kt
> +                        "driverLicenseKey",
Use static fields for keys

2022-09-15 09:29 UTC, catadarjan-tapptitude commented on app/src/main/java/com/internship/move/model/UserDataInternalStorageManager.kt
> +
Extra empty line

2022-09-15 09:29 UTC, catadarjan-tapptitude commented on app/src/main/java/com/internship/move/model/OnBoardingRepository.kt
> +        return userDataInternalStorageManager.getAuthPreferences()
Personally I prefer to inline very simple methods like this one
`suspend fun getAuthStatus(): UserResponse? = userDataInternalStorageManager.getAuthPreferences()`

2022-09-15 09:29 UTC, catadarjan-tapptitude commented on app/src/main/java/com/internship/move/model/appModule.kt
> +    OkHttpClient.Builder().addNetworkInterceptor(HttpLoggingInterceptor().setLevel(HttpLoggingInterceptor.Level.BODY)).build()
If you instantiate it like this, the interceptor will output console logs even on production release builds
Implement a way to add the LoggingInterceptor only on debug builds

2022-09-15 09:29 UTC, catadarjan-tapptitude commented on app/src/main/res/navigation/nav_graph_onboarding.xml
>      <fragment
Format this file to have empty lines between xml tags, similar to how you do it in UI xmls

2022-09-15 09:29 UTC, catadarjan-tapptitude commented on app/src/main/res/layout/fragment_license_confirm.xml
> +        android:layout_marginTop="120dp"
Extract raw values

2022-09-15 09:29 UTC, catadarjan-tapptitude commented on app/src/main/res/layout/fragment_license_confirm.xml
> +<?xml version="1.0" encoding="utf-8"?>
Only if you want: I think there's a way to implement this and instructions xml files using LinearLayout 🤔 
Don't spend too much time on it tho, I'm suggesting this only as a mental exercise to help you decide in the future what and how to choose parent/root ViewGroups

2022-09-15 09:29 UTC, catadarjan-tapptitude commented on app/src/main/java/com/internship/move/feature/licenseRegistration/LicenseRegistrationViewModel.kt
> +                licenseResponse.value = null
You'll want to show an error to the user in this case
Maybe have an error live data to observe (and set to null after showing it)

2022-09-16 09:19 UTC, IanisT227 commented on app/src/main/java/com/internship/move/feature/licenseRegistration/LicenseInstructionsFragment.kt
> +                        LicenseItem(args.userData.token, File(imageUri.path.toString()))
it says that the file cannot be found, that's why I stored it in that imageUri variable first

2022-09-19 08:39 UTC, IanisT227 commented on app/src/main/java/com/internship/move/feature/licenseRegistration/LicenseRegistrationViewModel.kt
> +    val licenseResponse: MutableLiveData<User?> = MutableLiveData()
I think you've got the only mutable live data in my project that could be just a simple variable, now that I'm looking at it :))
However, I will keep in mind and use this approach from now on, thanks for the advice!

2022-09-19 08:58 UTC, IanisT227 commented on app/src/main/java/com/internship/move/feature/licenseRegistration/LicenseRegistrationViewModel.kt
> +    val licenseResponse: MutableLiveData<User?> = MutableLiveData()
Actually I don't need that variable at all, oops

2022-09-19 10:38 UTC, merged