This is a mid-feature PR, the ride process doesn't fully work yet, however, you can book your scooter
IanisT227/ianis-internship-scooterapp pull request #9
Opened 2022-09-28 08:46 UTC by IanisT227

2022-09-28 12:40 UTC, IanisT227 commented
Implemented most of the ride flow

2022-10-03 10:31 UTC, catadarjan-tapptitude requested changes

2022-10-03 10:31 UTC, catadarjan-tapptitude commented on app/src/main/java/com/internship/move/feature/scooter_unlock/ScooterStateViewModel.kt
> +
Extra empty line

2022-10-03 10:31 UTC, catadarjan-tapptitude commented on app/src/main/res/drawable/bg_small_button.xml
> +        android:width="2dp"
Extract raw dimens and use specific colors

2022-10-03 10:31 UTC, catadarjan-tapptitude commented on app/src/main/res/drawable/ic_live_location.xml
> +        android:bottom="4dp"
Extract raw dimens

2022-10-03 10:31 UTC, catadarjan-tapptitude commented on app/src/main/res/drawable/ic_live_location.xml
> +        android:drawable="@drawable/ic_aaaaaa"
I think you should renaaaaaame this icon 😄

2022-10-03 10:31 UTC, catadarjan-tapptitude commented on app/src/main/res/layout/bottom_sheet_ride_info_card.xml
> +
Extra empty line

2022-10-03 10:31 UTC, catadarjan-tapptitude commented on app/src/main/res/layout/bottom_sheet_ride_info_card.xml
> +    app:cardCornerRadius="@dimen/bottom_sheet_corner_radius">
You can build this layout only using CL and a background shape drawable for top left & top right corners

2022-10-03 10:31 UTC, catadarjan-tapptitude commented on app/src/main/res/layout/bottom_sheet_scooter_start_ride.xml
> +<androidx.cardview.widget.CardView xmlns:android="http://schemas.android.com/apk/res/android"
You can build this layout only using CL and a background shape drawable for top left & top right corners

2022-10-03 10:31 UTC, catadarjan-tapptitude commented on app/src/main/res/layout/bottom_sheet_scooter_start_ride.xml
> +
Extra empty lines

2022-10-03 10:31 UTC, catadarjan-tapptitude commented on app/src/main/res/layout/bottom_sheet_scooter_start_ride.xml
> +            app:layout_constraintTop_toBottomOf="@+id/scooterIV" />
Refer to ids using `@id/`

2022-10-03 10:31 UTC, catadarjan-tapptitude commented on app/src/main/res/layout/bottom_sheet_scooter_start_ride.xml
> +            android:layout_marginHorizontal="24dp"
Extract raw dimens

2022-10-03 10:31 UTC, catadarjan-tapptitude commented on app/src/main/res/layout/fragment_successful_unlock.xml
> +        android:layout_marginBottom="106dp"
Extract raw dimens

2022-10-03 10:31 UTC, catadarjan-tapptitude commented on app/src/main/res/layout/fragment_successful_unlock.xml
> +
Extra empty line

2022-10-03 10:31 UTC, catadarjan-tapptitude commented on app/src/main/res/layout/fragment_unlock_by_code.xml
> +        android:layout_marginTop="108dp"
Extract raw dimens

2022-10-03 10:31 UTC, catadarjan-tapptitude commented on app/src/main/java/com/internship/move/MainActivity.kt
> +    private val onboardingViewModel: OnboardingViewModel by viewModel()
Why do you need these viewModels in MainActivity?
Let's discuss

2022-10-03 10:31 UTC, catadarjan-tapptitude commented on app/src/main/java/com/internship/move/feature/map/MapFragment.kt
> +                    .fillColor(ColorUtils.setAlphaComponent(resources.getColor(R.color.primary_dark_purple, null), 26)).radius(30.0)
Extract magic numbers to constants

2022-10-03 10:31 UTC, catadarjan-tapptitude commented on app/src/main/java/com/internship/move/feature/scooter_unlock/UnlockByCodeFragment.kt
> +            if (binding.codePinView.text?.length == 4) {
Extract magic number to constant

2022-10-03 10:31 UTC, catadarjan-tapptitude commented on app/src/main/java/com/internship/move/feature/scooter_unlock/UnlockSuccessfulFragment.kt
> +        Handler(Looper.getMainLooper()).postDelayed({
I suggest using a coroutine since it's lighter on memory and easier to cancel

2022-10-03 10:31 UTC, catadarjan-tapptitude commented on app/src/main/java/com/internship/move/model/appModule.kt
> +    val httpClient = OkHttpClient.Builder().readTimeout(60, TimeUnit.SECONDS)
Extract magic number to constant

2022-10-03 10:31 UTC, catadarjan-tapptitude commented on app/src/main/java/com/internship/move/feature/map/MapFragment.kt
> +            it.text = "$hh:$mm min"
I suggest creating an extension function for TextView that receives a Long timestamp and performs these transformations.
Also, you should use string res templates.
Extract magic numbers to constants

2022-10-03 10:31 UTC, catadarjan-tapptitude commented on app/src/main/java/com/internship/move/feature/map/MapFragment.kt
> +    private var rideStarted = false
I think these would be safer in the viewModel 🤔

2022-10-04 11:03 UTC, merged